### ISSUE TITLE
Create database with UserSession table, add migration script

### ISSUE THREAD

**Issue by andriimanzar** [andriimanzar/telegram-weather-forecast-bot#31]

**Comment by SamirFezani** [comment]
CREATE TABLE UserSession (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    start_time DATETIME NOT NULL,
    end_time DATETIME,
    FOREIGN KEY (user_id) REFERENCES User(id)
);
